name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    name: Run PR Agent on every pull request, respond to user comments
    
    steps:
    - name: PR Agent action step
      id: pragent
      uses: Codium-ai/pr-agent@main
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        github_action_config.auto_review: true
        github_action_config.auto_describe: true
        github_action_config.auto_improve: false
        
    - name: Comment PR Agent results
      if: steps.pragent.outputs.review_url
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🤖 **PR Agent Analysis Complete**\n\n' +
                  'Review: ${{ steps.pragent.outputs.review_url }}\n' +
                  'Description: ${{ steps.pragent.outputs.describe_url }}'
          });